NPA-5232: Add Backend Application (#15)
# Pull Request

## 🧾 Ticket Link

https://nhsd-jira.digital.nhs.uk/browse/NPA-5232

---

## 📄 Description/Summary of Changes

<!-- Describe the changes made in this PR. Include the
purpose/scope/impact/context of the changes -->

- Add backend application at `/app`
- Build docker container for app
- Add unit tests for app

---

## 🧪 Developer Testing Carried Out

<!-- Describe what tests (automated/unit/manual etc.) have been done for
the ticket. Include: -->
<!-- - Any tests added/updated -->
<!-- - Evidence that each acceptance criterion from the Jira ticket is
met -->

- Test evidence -
https://github.com/NHSDigital/im1-pfs-auth/pull/15#issuecomment-3140526697

---

## ✅ Developer Checklist

<!-- To be completed by the developer -->

- [x] I have set the PR title to follow the format: `NPA-XXXX:
<short-description>`
- [x] My branch name follows the convention:
`<type>/NPA-XXXX/<short-description>`
- [x] My commit messages follow the template: `NPA-XXXX:
<short-description>`
- [x] I have updated the documentation accordingly
- [x] I have set assignees and added appropriate labels

---

## 👀 Reviewer Checklist

<!-- To be completed by the reviewer -->

- [ ] Changes meet the acceptance criteria of the Jira ticket
- [ ] Code is able to be merged (no conflicts and adheres to coding
standards)
- [ ] Sufficient test evidence is provided (manual and/or automated)

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others
privacy, we kindly ask you to NOT including [PII (Personal Identifiable
Information) / PID (Personal Identifiable
Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public)
or any other sensitive data in this PR (Pull Request) and the codebase
changes. We will remove any PR that do contain any sensitive
information. We really appreciate your cooperation in this matter.

- [x] I confirm that neither PII/PID nor sensitive data are included in
this PR and the codebase changes.

diff --git a/.github/workflows/reusable-deploy.yml b/.github/workflows/reusable-deploy.yml
--- a/.github/workflows/reusable-deploy.yml
+++ b/.github/workflows/reusable-deploy.yml
@@ -1,7 +1,7 @@
 name: Deploy Environment
 
 concurrency:
-  group: deploy-${{ inputs.environment }}-${{ inputs.additional_path || 'default' }}
+  group: deploy-${{ inputs.environment }}-${{ inputs.type_of_deployment }}-${{ inputs.additional_path || 'default' }}
 
 on:
   workflow_call:
@@ -23,6 +23,7 @@ on:
         description: "Type of deployment, e.g. 'app', 'sandbox'"
         required: true
         type: string
+
     secrets:
       PROXYGEN_CLIENT_ID:
         required: true
@@ -41,8 +42,24 @@ env:
   PROXYGEN_DOCKER_REGISTRY_URL: 958002497996.dkr.ecr.eu-west-2.amazonaws.com/im1-pfs-auth
 
 jobs:
+  validate-inputs:
+    name: "Validate Inputs"
+    runs-on: ubuntu-latest
+    steps:
+      - name: "Check type_of_deployment input"
+        run: |
+          case "${{ inputs.environment }}" in
+            internal-dev|internal-dev-sandbox)
+              ;;
+            *)
+              echo "Invalid environment: ${{ inputs.environment }}. Allowed values are: internal-dev, internal-dev-sandbox."
+              exit 1
+              ;;
+          esac
+
   build-and-push-container:
     name: "Build & Push Container"
+    needs: validate-inputs
     runs-on: ubuntu-latest
     steps:
       - name: "Checkout code"
@@ -59,7 +76,7 @@ jobs:
           PROXYGEN_KEY_ID: ${{ secrets.PROXYGEN_KEY_ID }}
           PROXYGEN_PRIVATE_KEY: ${{ secrets.PROXYGEN_PRIVATE_KEY }}
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
       - name: "Build ${{inputs.type_of_deployment}} container"
         run: make ${{inputs.type_of_deployment}}-build
       - name: Check Docker Containers
