NPA-5232: Add container deploy workflow

diff --git a/.github/workflows/reusable-deploy.yml b/.github/workflows/reusable-deploy.yml
--- a/.github/workflows/reusable-deploy.yml
+++ b/.github/workflows/reusable-deploy.yml
@@ -23,6 +23,10 @@ on:
         description: "Type of deployment, e.g. 'app', 'sandbox'"
         required: true
         type: string
+<<<<<<< HEAD
+=======
+
+>>>>>>> e58f3e2 (NPA-5232: Add container deploy workflow)
     secrets:
       PROXYGEN_CLIENT_ID:
         required: true
@@ -41,8 +45,24 @@ env:
   PROXYGEN_DOCKER_REGISTRY_URL: 958002497996.dkr.ecr.eu-west-2.amazonaws.com/im1-pfs-auth
 
 jobs:
+  validate-inputs:
+    name: "Validate Inputs"
+    runs-on: ubuntu-latest
+    steps:
+      - name: "Check type_of_deployment input"
+        run: |
+          case "${{ inputs.environment }}" in
+            internal-dev|internal-dev-sandbox)
+              ;;
+            *)
+              echo "Invalid environment: ${{ inputs.environment }}. Allowed values are: internal-dev, internal-dev-sandbox."
+              exit 1
+              ;;
+          esac
+
   build-and-push-container:
     name: "Build & Push Container"
+    needs: validate-inputs
     runs-on: ubuntu-latest
     steps:
       - name: "Checkout code"
@@ -69,6 +89,7 @@ jobs:
 
   deploy-environment:
     name: "Deploy Environment"
+    needs: build-container
     runs-on: ubuntu-latest
     needs: build-and-push-container
     environment:
